package com.se.ecostruxure_mmirzakhani.be;

public enum Currency {

    //Currencies extracted from eur.xml
    EURO("Euro", "EUR"),
    USD("US Dollar", "USD"),
    GBP("British Pound", "GBP"),
    AUD("Australian Dollar", "AUD"),
    CAD("Canadian Dollar", "CAD"),
    CNY("Chinese Yuan", "CNY"),
    HKD("Hong Kong Dollar", "HKD"),
    IDR("Indonesian Rupiah", "IDR"),
    INR("Indian Rupee", "INR"),
    JPY("Japanese Yen", "JPY"),
    KRW("South Korean Won", "KRW"),
    MYR("Malaysian Ringgit", "MYR"),
    NZD("New Zealand Dollar", "NZD"),
    PHP("Philippine Peso", "PHP"),
    SGD("Singapore Dollar", "SGD"),
    THB("Thai Baht", "THB"),
    TWD("New Taiwan Dollar", "TWD"),
    VND("Vietnamese Dong", "VND"),
    AED("U.A.E Dirham", "AED"),
    BGN("Bulgarian Lev", "BGN"),
    BRL("Brazilian Real", "BRL"),
    CHF("Swiss Franc", "CHF"),
    CZK("Czech Koruna", "CZK"),
    DKK("Danish Krone", "DKK"),
    EGP("Egyptian Pound", "EGP"),
    HUF("Hungarian Forint", "HUF"),
    MDL("Moldova Lei", "MDL"),
    MXN("Mexican Peso", "MXN"),
    NOK("Norwegian Krone", "NOK"),
    PLN("Polish Zloty", "PLN"),
    RON("Romanian New Leu", "RON"),
    RSD("Serbian Dinar", "RSD"),
    RUB("Russian Rouble", "RUB"),
    SEK("Swedish Krona", "SEK"),
    TRY("Turkish Lira", "TRY"),
    UAH("Ukrainian Hryvnia", "UAH"),
    ZAR("South African Rand", "ZAR"),
    AFN("Afghan afghani", "AFN"),
    ALL("Albanian lek", "ALL"),
    AMD("Armenia Dram", "AMD"),
    ANG("Neth. Antillean Guilder", "ANG"),
    AOA("Angolan kwanza", "AOA"),
    ARS("Argentine Peso", "ARS"),
    AWG("Aruban florin", "AWG"),
    AZN("Azerbaijan Manat", "AZN"),
    BAM("Bosnia and Herzegovina convertible mark", "BAM"),
    BBD("Barbadian Dollar", "BBD"),
    BDT("Bangladeshi taka", "BDT"),
    BHD("Bahrain Dinar", "BHD"),
    BIF("Burundian franc", "BIF"),
    BND("Brunei Dollar", "BND"),
    BOB("Bolivian Boliviano", "BOB"),
    BSD("Bahamian Dollar", "BSD"),
    BWP("Botswana Pula", "BWP"),
    BYN("Belarussian Ruble", "BYN"),
    BZD("Belize dollar", "BZD"),
    CDF("Congolese franc", "CDF"),
    CLP("Chilean Peso", "CLP"),
    COP("Colombian Peso", "COP"),
    CRC("Costa Rican Colón", "CRC"),
    CUP("Cuban peso", "CUP"),
    CVE("Cape Verde escudo", "CVE"),
    DJF("Djiboutian franc", "DJF"),
    DOP("Dominican Peso", "DOP"),
    DZD("Algerian Dinar", "DZD"),
    ERN("Eritrean nakfa", "ERN"),
    ETB("Ethiopian birr", "ETB"),
    FJD("Fiji Dollar", "FJD"),
    GEL("Georgian lari", "GEL"),
    GHS("Ghanaian Cedi", "GHS"),
    GIP("Gibraltar pound", "GIP"),
    GMD("Gambian dalasi", "GMD"),
    GNF("Guinean franc", "GNF"),
    GTQ("Guatemalan Quetzal", "GTQ"),
    GYD("Guyanese dollar", "GYD"),
    HNL("Honduran Lempira", "HNL"),
    HTG("Haitian gourde", "HTG"),
    ILS("Israeli New Sheqel", "ILS"),
    IQD("Iraqi dinar", "IQD"),
    IRR("Iranian rial", "IRR"),
    ISK("Icelandic Krona", "ISK"),
    JMD("Jamaican Dollar", "JMD"),
    JOD("Jordanian Dinar", "JOD"),
    KES("Kenyan shilling", "KES"),
    KGS("Kyrgyzstan Som", "KGS"),
    KHR("Cambodian riel", "KHR"),
    KMF("Comoro franc", "KMF"),
    KWD("Kuwaiti Dinar", "KWD"),
    KZT("Kazakhstani Tenge", "KZT"),
    LAK("Lao kip", "LAK"),
    LBP("Lebanese Pound", "LBP"),
    LKR("Sri Lanka Rupee", "LKR"),
    LRD("Liberian dollar", "LRD"),
    LSL("Lesotho loti", "LSL"),
    LYD("Libyan Dinar", "LYD"),
    MAD("Moroccan Dirham", "MAD"),
    MGA("Malagasy ariary", "MGA"),
    MKD("Macedonian denar", "MKD"),
    MMK("Myanma Kyat", "MMK"),
    MNT("Mongolian togrog", "MNT"),
    MOP("Macanese pataca", "MOP"),
    MRU("Mauritanian ouguiya", "MRU"),
    MUR("Mauritian Rupee", "MUR"),
    MVR("Maldivian rufiyaa", "MVR"),
    MWK("Malawian kwacha", "MWK"),
    MZN("Mozambican metical", "MZN"),
    NAD("Namibian dollar", "NAD"),
    NGN("Nigerian Naira", "NGN"),
    NIO("Nicaraguan Córdoba", "NIO"),
    NPR("Nepalese Rupee", "NPR"),
    OMR("Omani Rial", "OMR"),
    PAB("Panamanian Balboa", "PAB"),
    PEN("Peruvian Nuevo Sol", "PEN"),
    PGK("Papua New Guinean kina", "PGK"),
    PKR("Pakistani Rupee", "PKR"),
    PYG("Paraguayan Guaraní", "PYG"),
    QAR("Qatari Rial", "QAR"),
    RWF("Rwandan franc", "RWF"),
    SAR("Saudi Riyal", "SAR"),
    SBD("Solomon Islands dollar", "SBD"),
    SCR("Seychelles rupee", "SCR"),
    SDG("Sudanese pound", "SDG"),
    SOS("Somali shilling", "SOS"),
    SRD("Surinamese dollar", "SRD"),
    SSP("South Sudanese pound", "SSP"),
    STN("São Tomé and Príncipe Dobra", "STN"),
    SVC("Salvadoran colon", "SVC"),
    SYP("Syrian pound", "SYP"),
    SZL("Swazi lilangeni", "SZL"),
    TJS("Tajikistan Ruble", "TJS"),
    TMT("New Turkmenistan Manat", "TMT"),
    TND("Tunisian Dinar", "TND"),
    TOP("Tongan paʻanga", "TOP"),
    TTD("Trinidad Tobago Dollar", "TTD"),
    TZS("Tanzanian shilling", "TZS"),
    UGX("Ugandan shilling", "UGX"),
    UYU("Uruguayan Peso", "UYU"),
    UZS("Uzbekistan Sum", "UZS"),
    VES("Venezuelan Bolivar", "VES"),
    VUV("Vanuatu vatu", "VUV"),
    WST("Samoan tala", "WST"),
    XAF("Central African CFA Franc", "XAF"),
    XCD("East Caribbean Dollar", "XCD"),
    XOF("West African CFA Franc", "XOF"),
    XPF("CFP Franc", "XPF"),
    YER("Yemeni rial", "YER"),
    ZMW("Zambian kwacha", "ZMW");
    private final String displayName;
    private final String currencyCode;

    Currency(String displayName, String currencyCode) {
        this.displayName = displayName;
        this.currencyCode = currencyCode;
    }

    public String getDisplayName() {
        return displayName;
    }

    public String getCurrencyCode() {
        return currencyCode;
    }


    public static Currency getByCurrencyCode(String currencyCode) {
        for (Currency currency : values()) {
            if (currency.getCurrencyCode().equalsIgnoreCase(currencyCode)) {
                return currency;
            }
        }
        return null; // ToDO
    }
}
