package com.se.ecostruxure_mmirzakhani.utils;

public enum WindowType {
    LOADING,
    MAIN,
    EMPLOYEE_DASHBOARD,
    CREATE_EMPLOYEE,
    MULTIPLIERS,
    CALCULATOR,
    TEAMS,
    DASHBOARD,
    TEAM, SCRIPT, SCRIPT_CONTENT, PROGRESS_BAR, EMPLOYEE,
    PROJECT_MAIN,
    PROJECT_MANAGER,
    CREATE_PROJECT,
    EMPLOYEE_MAIN,
    ASSIGN_EMPLOYEE_PROJECT;
}
